name: env 
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9.18
 - pip
 - pandas
 - numpy
 - plotly
 - matplotlib
 - seaborn
 - scikit-learn
 - streamlit
 - joblib
 - xgboost
 - statsmodels
 - scikit-optimize